# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWLaZ1m2KZL8gRubGkJ55bOgmEo4-e5V
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Função para gerar dados de exemplo para cada mês
def gerar_dados_exemplo():
    meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 
             'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
    dados = {mes: {
        "Receitas": {},  # Agora as receitas são um dicionário com nome e valor
        "Despesas": {}   # Agora as despesas são um dicionário com nome e valor
        } for mes in meses}
    return dados

# Inicializar os dados no session_state se ainda não estiverem definidos
if 'dados_por_mes' not in st.session_state:
    st.session_state.dados_por_mes = gerar_dados_exemplo()

# Função para exibir o resumo de um mês com estilo futurístico
def exibir_resumo_mes(mes, dados_mes):
    total_receitas = sum(dados_mes['Receitas'].values())
    total_despesas = sum(dados_mes['Despesas'].values())
    
    # Verificar se as despesas estão acima das receitas e alertar
    if total_despesas > total_receitas:
        st.error(f"Atenção! As despesas estão acima das receitas em {mes}.")
    
    st.markdown(f"""
    <div style='background-color:#1e1e2e; padding:20px; border-radius:15px; margin-bottom:10px; color:#fff;'>
        <h4 style='text-align:center;'>{mes} 2023</h4>
        <p><b>Total de Receitas:</b> R$ {total_receitas:.2f}</p>
        <p><b>Total de Despesas:</b> R$ {total_despesas:.2f}</p>
    </div>
    """, unsafe_allow_html=True)

# Função para calcular a distribuição em porcentagens
def calcular_percentuais(dados_mes):
    total_receitas = sum(dados_mes['Receitas'].values())
    total_despesas = sum(dados_mes['Despesas'].values())
    
    try:
        total = total_receitas + total_despesas
        if total == 0:
            return [0, 0]
        percent_receitas = (total_receitas / total) * 100
        percent_despesas = (total_despesas / total) * 100
        return [percent_receitas, percent_despesas]
    except:
        return [0, 0]

# Função para gerar o gráfico de pizza
def gerar_grafico_pizza(mes):
    dados_mes = st.session_state.dados_por_mes[mes]
    percentuais = calcular_percentuais(dados_mes)
    df_percent = pd.DataFrame({
        'Categoria': ['Receitas', 'Despesas'],
        'Percentual': percentuais
    })
    fig = px.pie(df_percent, values='Percentual', names='Categoria', title=f'Distribuição em {mes}')
    st.plotly_chart(fig)

# Função para gerar o gráfico anual de linha
def gerar_grafico_anual():
    resumo = {"Meses": [], "Receitas": [], "Despesas": []}
    for mes, dados in st.session_state.dados_por_mes.items():
        resumo['Meses'].append(mes)
        resumo['Receitas'].append(sum(dados['Receitas'].values()))
        resumo['Despesas'].append(sum(dados['Despesas'].values()))
    
    df_resumo = pd.DataFrame(resumo)
    fig = px.line(df_resumo, x='Meses', y=['Receitas', 'Despesas'], title="Evolução Anual de Receitas e Despesas")
    st.plotly_chart(fig)

# Função para exportar os dados para CSV
def exportar_csv():
    df = pd.DataFrame(st.session_state.dados_por_mes).T  # Transpor para ficar mais fácil de ler
    return df.to_csv().encode('utf-8')

# Função para processar upload de arquivo CSV ou Excel
def processar_upload(arquivo):
    if arquivo is not None:
        try:
            # Processar CSV
            if arquivo.name.endswith('.csv'):
                dados = pd.read_csv(arquivo)
            # Processar Excel
            elif arquivo.name.endswith('.xlsx'):
                dados = pd.read_excel(arquivo)
            else:
                st.error('Formato de arquivo não suportado. Faça o upload de CSV ou Excel.')
                return None
            return dados
        except Exception as e:
            st.error(f"Ocorreu um erro ao processar o arquivo: {e}")
            return None
    return None

# Sidebar para upload de CSV ou Excel
st.sidebar.header('Upload de Arquivo')
arquivo = st.sidebar.file_uploader("Faça o upload do arquivo CSV ou Excel", type=['csv', 'xlsx'])
dados_upload = processar_upload(arquivo)

if dados_upload is not None:
    st.sidebar.write('Dados do arquivo:')
    st.sidebar.write(dados_upload)

# Sidebar para download de CSV
st.sidebar.header('Download dos Dados')
csv = exportar_csv()
st.sidebar.download_button(
    label="Baixar dados em CSV",
    data=csv,
    file_name='orcamento_financeiro.csv',
    mime='text/csv',
)

# Página principal
st.title('Planejamento Financeiro - Meses do Ano')

# Layout futurístico para Resumo dos Meses
st.markdown('---')
st.markdown('<h2 style="text-align:center; color:#42b883;">Resumo dos Meses</h2>', unsafe_allow_html=True)

col1, col2, col3 = st.columns(3)
meses = list(st.session_state.dados_por_mes.keys())

for i, mes in enumerate(meses):
    col = [col1, col2, col3][i % 3]  # Distribuir os meses entre as colunas
    with col:
        exibir_resumo_mes(mes, st.session_state.dados_por_mes[mes])

# Seção de edição de Receitas e Despesas com caixa expansível após seleção do mês
st.markdown('---')
st.markdown('<h2 style="text-align:center; color:#42b883;">Editar Receitas e Despesas</h2>', unsafe_allow_html=True)

mes_selecionado = st.selectbox("Selecione o mês para editar", meses)

# Caixa expansível para editar dados do mês selecionado
with st.expander(f"Lançamento de {mes_selecionado}"):
    st.write(f"Receitas em {mes_selecionado}")
    n_receitas = st.number_input("Quantas receitas você quer adicionar?", min_value=1, step=1, key=f"n_receitas_{mes_selecionado}")
    for i in range(n_receitas):
        nome_receita = st.text_input(f"Nome da receita {i+1}", key=f"nome_receita_{i}_{mes_selecionado}")
        valor_receita = st.number_input(f"Valor da receita {i+1} (R$)", min_value=0.0, step=100.0, key=f"valor_receita_{i}_{mes_selecionado}")
        st.session_state.dados_por_mes[mes_selecionado]['Receitas'][nome_receita] = valor_receita

    st.write(f"Despesas em {mes_selecionado}")
    n_despesas = st.number_input("Quantas despesas você quer adicionar?", min_value=1, step=1, key=f"n_despesas_{mes_selecionado}")
    for i in range(n_despesas):
        nome_despesa = st.text_input(f"Nome da despesa {i+1}", key=f"nome_despesa_{i}_{mes_selecionado}")
        valor_despesa = st.number_input(f"Valor da despesa {i+1} (R$)", min_value=0.0, step=100.0, key=f"valor_despesa_{i}_{mes_selecionado}")
        st.session_state.dados_por_mes[mes_selecionado]['Despesas'][nome_despesa] = valor_despesa

# Gráfico de Pizza
st.markdown('---')
st.subheader('Gráfico de Pizza (Selecione o Mês)')
gerar_grafico_pizza(mes_selecionado)

# Gráfico Anual de Linha
st.markdown('---')
st.subheader('Gráfico Anual de Linha')
gerar_grafico_anual()

